### ISSUE TITLE
Justification for delay

### ISSUE THREAD

**Issue by KhyatiShah** [Promact/requirement-management#6]
Sometimes we are asked for the reason for delay of work due to roadblocks. These roadblocks are normally mentioned in the task we are working in Redmine (Project Management tool). 
Moreover, justification is asked when module development is completed or is on verge of completion. So, at that time if many tasks are done and if there is a list of roadblocks, it becomes difficult to search by opening each task for the reason of delay.
So, for each module, we can have integration of Feature of Redmine with this software. So, whenever justification needs to be send we can just refer from the comments of module.

**Comment by chintans** [comment]
I think this more of an issue of project management than requirement management. This issue can be tackled separately in a different project. If you agree we can close the issue for now.
