### ISSUE TITLE
Track of Team members work

### ISSUE THREAD

**Issue by DhrutiShah** [Promact/requirement-management#8]
We are working in a process, where we provide the estimation of the feature and calculate the estimated time v/s actual time after completion of that feature. In redmine we can't easily find out the actual time v/s estimated time for each of the team members for individual feature. perhaps also not able to find out the how many bugs are assigned for particular that feature. and they are major or silly bugs. 

if we can find this out easily, we can get the productive work of any team member easily.

**Comment by VishalKumarMitra786** [comment]
Not to offend but I find this to be more of an additive functionality than an issue. It is irrelevant to requirement management as it seems to be more of Project Tracking Management System. Hope this should be marked closed if you agree on it.
